#include "util/lpm_python3_util.hpp"
#include "util/lpm_filename.hpp"
#include "util/lpm_string_util.hpp"
#include "lpm_assert.hpp"
#include <sstream>

namespace Lpm {

void PythonModule::init() {
  os << "# this module was automatically generated by LPM\n";
  os << "import numpy as np\n\n";
  os << "# Object is just a dynamic container\n";
  os << "class Object(object):\n";
  auto tabstr = indent_string(1);
  os << tabstr << "pass\n\n";
  is_init = true;
}

void PythonModule::dataset_init(const std::string& dataset_name) {
  LPM_REQUIRE(is_init);
  os << dataset_name << " = Object()\n";
  ++tab_level;
}

}
