#!/bin/bash

VTK_SRC=$HOME/VTK-9.5.1
BLD_DIR=$VTK_SRC/build-openmp
LPM_TPL_DIR=$HOME/lpm-tpl-openmp

cmake -B $BLD_DIR \
-DCMAKE_INSTALL_PREFIX=$LPM_TPL_DIR \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DVTK_USE_CUDA=OFF \
-DVTK_USE_MPI=ON \
-DVTK_WRAP_PYTHON=OFF \
-DVTK_USE_EXTERNAL=OFF \
-GNinja \
$VTK_SRC