#!/bin/bash

CATCH2_SRC=$HOME/Catch2 
TPL_DIR=$HOME/lpm-tpl-cuda
BLD_DIR=$CATCH2_SRC/build

rm -rf $BLD_DIR/CMake*

cmake -B $BLD_DIR \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_BUILD_TYPE=RELEASE \
-DBUILD_SHARED_LIBS=OFF \
-DCATCH_INSTALL_DOCS=OFF \
-DCATCH_INSTALL_EXTRAS=OFF \
-DCATCH_BUILD_TESTING=OFF \
$CATCH2_SRC