#!/bin/bash

SPDLOG_SRC=$HOME/spdlog 
TPL_DIR=$LPM_TPL_DIR
BLD_DIR=$SPDLOG_SRC/build

rm -rf $BLD_DIR/CMake*

cmake -B $BLD_DIR \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_BUILD_TYPE=RELEASE \
-DBUILD_SHARED_LIBS=OFF \
-DSPDLOG_BUILD_EXAMPLE=OFF \
-DSPDLOG_BUILD_TESTS=OFF \
-DSPDLOG_ENABLE_PCH=ON \
-DSPDLOG_INSTALL=ON \
$SPDLOG_SRC