#!/bin/bash

rm -rf CMake*

KOKKOS_KERNELS_SRC=$HOME/kokkos-kernels
KOKKOS_INSTALL_DIR=$HOME/kokkos-debug/install

cmake \
-DCMAKE_INSTALL_PREFIX=$KOKKOS_INSTALL_DIR \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_BUILD_TYPE=DEBUG \
-DKokkos_ROOT=$KOKKOS_INSTALL_DIR \
$KOKKOS_KERNELS_SRC
