name: auto_test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'tools/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'tools/**'
      - 'README.md'

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds LPM and runs our test suite.
  auto-test:
    # A build matrix storing all desired configurations.
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04] #, macos-latest]
        build-type: [Debug, RelWithDebInfo]
        dfs-option: [OFF, ON]

    runs-on: ${{ matrix.os }}

    # Pre-fab container with third-party libs installed.
    container: pbosler/lpm-tpl-sep25:0

    # Environment variables
    env:
      CC: mpicc
      CXX: mpicxx
      FC: mpifort
      VTK_ROOT: /tpl
      KOKKOS_ROOT: /tpl
      DOCKER_ALLOW_MPI_RUN_AS_ROOT: 1
      DOCKER_ALLOW_MPI_RUN_AS_ROOT_CONFIRM: 1
      OMP_NUM_THREADS: 4
      OMP_PROC_BIND: spread
      OMP_PLACES: threads
      LPM_INSTALL: /lpm-install
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    # Steps for building and running tests.
    steps:
    - name: Cache git folder
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/.git
        key: git-folder

    - name: Check out lpm
      uses: actions/checkout@v4
      with:
        path: ${{github.workspace}}

    - name: Configure lpm (${{ matrix.build-type }} DFS ${{ matrix.dfs-option }})
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cmake -B ./build \
          -DCMAKE_INSTALL_PREFIX=$LPM_INSTALL \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_CXX_COMPILER=mpicxx \
          -DCMAKE_C_COMPILER=mpicc \
          -DCMAKE_Fortran_COMPILER=mpifort \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_PREFIX_PATH=/lpm-tpl \
          -DLPM_ENABLE_NETCDF=OFF \
          -DLPM_ENABLE_DFS=${{ matrix.dfs-option }} \
          -DLPM_ENABLE_Compose=ON \
          -DKokkos_DIR=/tpl \
          -DKokkosKernels_DIR=/tpl \
          -DCompadre_DIR=/tpl \
          -DCompose_DIR=/tpl \
          -DSPDLOG_DIR=/tpl \
          -DCATCH2_DIR=/tpl \
          -DFFTW3_DIR=/tpl \
          -DFINUFFT_DIR=/tpl \
          -G "Unix Makefiles" \
          .

    - name: Build lpm ${{ matrix.build-type }} DFS ${{ matrix.dfs-option }}
      working-directory: ${{github.workspace}}
      run: cmake --build ./build --config ${{ matrix.build-type }}

    - name: Test lpm ${{ matrix.build-type }} DFS ${{ matrix.dfs-option }}
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C ${{ matrix.build-type }} --no-tests=error

