name: auto_test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds LPM and runs our test suite.
  build:
    # A build matrix storing all desired configurations.
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        build-type: [Debug, RelWithDebInfo]

    runs-on: ${{ matrix.os }}

    # Pre-fab container with third-party libs installed.
    container: pbosler/lpm-tpl-release:1

    # Environment variables
    env:
      CC: mpicc
      CXX: mpicxx
      FC: mpifort
      VTK_ROOT: /vtk
      KOKKOS_ROOT: /lpm-tpl
      DOCKER_ALLOW_MPI_RUN_AS_ROOT: 1
      DOCKER_ALLOW_MPI_RUN_AS_ROOT_CONFIRM: 1
      GIT_SSL_NO_VERIFY: 1

    # Steps for building and running tests.
    steps:
    - name: Checking out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure lpm (${{ matrix.build-type }})
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_INSTALL_PREFIX=`pwd`/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_CXX_COMPILER=mpicxx \
          -DCMAKE_C_COMPILER=mpicc \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DLPM_ENABLE_NETCDF=OFF \
          -DLPM_ENABLE_VTK=ON \
          -DLPM_ENABLE_Compose=ON \
          -DLPM_ENABLE_DFS=OFF \
          -DKokkos_DIR=/lpm-tpl \
          -DKokkosKernels_DIR=/lpm-tpl \
          -DCompadre_DIR=/lpm-tpl \
          -DCompose_DIR=/lpm-tpl \
          -G "Unix Makefiles" \
          ..

    - name: Build lpm ${{ matrix.build-type }}
      run: |
        cd build
        make -j 8

    - name: Run tests ${{ matrix.build-type }}
      run: |
        cd build
        ctest -V

